title: Codex 2023
description: Code & Exploit
theme: just-the-docs
favicon_ico: '/assets/images/favicon.png'

url: https://noverdy.github.io/codex-rulebook

color_scheme: dark

ga_tracking: G-4FX767E4K6
ga_tracking_anonymize_ip: true
