title: Codex 2023
description: Rulebook
theme: just-the-docs

url: https://noverdy.github.io/codex-rulebook

aux_links:
  Template Repository: https://github.com/noverdy/codex-rulebook

color_scheme: dark
